name: "Subscribe to Label"
description: "Allows users to subscribe to a label and automatically get @'d when the label is added to a pull request or issue"
inputs:
  repo-token:
    description: "GITHUB_TOKEN secret"
    required: true
  users:
    description: "A map from username to the list of labels they are subscribed to"
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
