name: "Subscribe to Label"
description: "Allows users to subscribe to a label and automatically get @'d when the label is added to a pull request or issue"
inputs:
  repo-token:
    description: "GITHUB_TOKEN secret"
    required: true
  configuration-path:
    description: "The path for the user and label configurations"
    default: ".github/subscribe-to-label.json"
runs:
  using: 'node12'
  main: 'dist/index.js'
